apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-iso-matcher
  labels:
    app: country-iso-matcher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country-iso-matcher
  template:
    metadata:
      labels:
        app: country-iso-matcher
    spec:
      containers:
        - name: country-iso-matcher
          image: country-iso-service-go:latest
          ports:
            - containerPort: 3030
          env:
            - name: ENV
              value: "production"
            - name: PORT
              value: "3030"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3030
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: country-iso-matcher-service
spec:
  selector:
    app: country-iso-matcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: LoadBalancer